local Util = require("stilla.util")

local M = {}

---@type stilla.HighlightsFn
function M.get(c, opts)
  local result = {
    ["@annotation"] = "PreProc",
    ["@attribute"] = { fg = c.language },
    ["@boolean"] = "Boolean",
    ["@character"] = "Character",
    ["@character.print"] = "SpecialChar",
    ["@character.special"] = "SpecialChar",
    ["@comment"] = "Comment",
    ["@comment.error"] = { fg = c.error },
    ["@comment.hint"] = { fg = c.hint },
    ["@comment.info"] = { fg = c.info },
    ["@comment.note"] = { fg = c.hint },
    ["@comment.todo"] = { fg = c.attention },
    ["@comment.warning"] = { fg = c.warning },
    ["@constant"] = "Constant",
    ["@constant.builtin"] = { fg = c.special },
    ["@constant.macro"] = "Define",
    ["@constructor"] = { fg = c.function_decl },
    ["@constructor.tsx"] = "@constructor",
    ["@diff.delta"] = "DiffChange",
    ["@diff.minus"] = "DiffDelete",
    ["@diff.plus"] = "DiffAdd",
    ["@function"] = "Function",
    ["@function.builtin"] = { fg = c.builtin },
    ["@function.macro"] = "Macro",
    ["@function.method"] = "Function",
    ["@function.method.call"] = { fg = c.language },
    ["@function.call"] = { fg = c.language },
    ["@keyword"] = "Keyword",
    ["@keyword.conditional"] = "Conditional",
    ["@keyword.coroutine"] = "@keyword",
    ["@keyword.debug"] = "Debug",
    ["@keyword.directive"] = "PreProc",
    ["@keyword.directive.define"] = "Define",
    ["@keyword.exception"] = "Exception",
    ["@keyword.function"] = "Keyword",
    ["@keyword.import"] = { fg = c.language },
    ["@keyword.operator"] = "@operator",
    ["@keyword.repeat"] = "Repeat",
    ["@keyword.return"] = "@keyword",
    ["@keyword.storage"] = "StorageClass",
    -- ["@label"] = { fg = c.platinum },
    -- ["@markup"] = "@none",
    -- ["@markup.emphasis"] = "Italic",
    -- ["@markup.environment"] = "Macro",
    -- ["@markup.environment.name"] = "Type",
    -- ["@markup.heading"] = "Title",
    -- ["@markup.italic.markdown_inline"] = { fg = c.munsell, italic = true },
    -- ["@markup.italic"] = "Italic",
    -- ["@markup.link"] = { fg = c.teal },
    -- ["@markup.link.label"] = "SpecialChar",
    -- ["@markup.link.label.symbol"] = "Identifier",
    -- ["@markup.link.url"] = "Underlined",
    -- ["@markup.list"] = "Special",
    -- ["@markup.list.checked"] = { fg = c.asparagus },
    -- ["@markup.list.markdown"] = { fg = c.arylide, bold = true },
    -- ["@markup.list.unchecked"] = { fg = c.mountbatten },
    -- ["markup.math"] = { fg = c.moonstone },
    ["@markup.raw"] = "String",
    -- ["@markup.raw.markdown_inline"] = { bg = c.bg_visual, fg = c.munsell },
    -- ["@markup.strikethrough"] = { strikethrough = true },
    -- ["@markup.strong.markdown_inline"] = { fg = c.khaki, bold = true },
    ["@markup.strong"] = "Bold",
    ["@module"] = "Include",
    -- ["@module.builtin"] = { fg = c.teal, italic = true },
    ["@namespace.builtin"] = "@variable.builtin",
    ["@none"] = {},
    ["@number"] = "Number",
    ["@number.float"] = "Float",
    -- ["@operator"] = { fg = c.vanilla },
    -- ["@property"] = { fg = c.timberwolf },
    ["@punctuation.bracket"] = "Delimiter",
    ["@punctuation.delimiter"] = "Delimiter",
    ["@punctuation.special"] = "Delimiter",
    ["@string"] = "String",
    ["@string.documentation"] = "String",
    ["@string.escape"] = { fg = c.escape },
    ["@string.regexp"] = { fg = c.regexp },
    ["@tag"] = { fg = c.fg },
    ["@tag.attribute"] = { fg = c.language },
    ["@tag.delimiter"] = "Delimiter",
    -- ["@tag.delimiter.tsx"] = { fg = Util.blend_bg(c.pink, 0.7) },
    -- ["@tag.tsx"] = { fg = c.old_gold },
    -- ["@tag.javascript"] = { fg = c.old_gold },
    ["@type"] = "Type",
    ["@type.builtin"] = "Type",
    ["@type.definition"] = "Typedef",
    ["@type.qualifier"] = "@keyword",
    ["@variable"] = { fg = c.local_var, style = opts.styles.variables },
    ["@variable.builtin"] = { fg = c.builtin },
    ["@variable.member"] = { fg = c.language },
    -- ["@variable.parameter"] = { fg = c.fg },
    ["@variable.parameter.builtin"] = { fg = c.builtin },
    --
    -- -- Angular ──────────────────────────────────────────────────────────────────────
    ["@keyword.conditional.angular"] = "@keyword.conditional",
    ["@keyword.repeat.angular"] = "@keyword.repeat",
    ["@punctuation.special.angular"] = "@punctuation.bracket",
    ["@tag.angular"] = "@tag",
    ["@tag.attribute.angular"] = "@tag.attribute",
    ["@tag.delimiter.angular"] = "@tag.delimiter",
    ["@variable.angular"] = { fg = c.local_var },
  }

  -- for i, color in ipairs(c.rainbow) do
  --   result["@markup.heading." .. i .. ".markdown"] = { fg = color, bold = true }
  -- end
  --
  return result
end

return M
